import { Question, Section, DiscProfile } from "@/types";

export const SECTIONS: Section[] = [
  { label: "Section 1 — Everyday Reactions & Inner World", range: [1, 5] },
  { label: "Section 2 — How You Handle People & Conflict", range: [6, 10] },
  { label: "Section 3 — Business Instinct & Emotional Recovery", range: [11, 15] },
  { label: "Section 4 — Risk, Recognition & Your Vision", range: [16, 20] },
];

export const QUESTIONS: Question[] = [
  {
    id: 1,
    section: 1,
    tag: "DAILY LIFE · MORNING ROUTINE",
    text: "It is 7 AM. You have a full day ahead. What does your morning look like?",
    instruction: "Don't overthink — just pick what feels most natural to you.",
    options: {
      A: "I am already working. I check yesterday's results and plan my moves for today.",
      B: "I scroll through my phone, reply to messages, and catch up with people I care about.",
      C: "I have a quiet routine — tea, a walk maybe. I like to ease into the day peacefully.",
      D: "I review my schedule and to-do list to make sure everything is organised before I start.",
    },
  },
  {
    id: 2,
    section: 1,
    tag: "PEOPLE & RELATIONSHIPS · A FRIEND IN TROUBLE",
    text: "Your close friend calls you upset — their business is struggling badly. What do you do first?",
    instruction: "There is no correct answer here — just go with your gut.",
    options: {
      A: "I immediately start listing things they should fix and push them to act now.",
      B: "I listen, empathise, then start energising them — 'You've got this, let's go!'",
      C: "I sit with them, let them talk it out fully, and just be present without rushing.",
      D: "I ask questions to understand exactly what went wrong before suggesting anything.",
    },
  },
  {
    id: 3,
    section: 1,
    tag: "EVERYDAY STRESS · TRAFFIC JAM",
    text: "You are stuck in Chennai traffic and already 20 minutes late to an important meeting. Your reaction?",
    instruction: "Be honest — what actually goes through your mind?",
    options: {
      A: "I am frustrated and I call ahead immediately to take control of the situation.",
      B: "I text the person something warm or funny so they do not feel bad waiting.",
      C: "I feel anxious but stay calm — I focus on breathing and arriving safely.",
      D: "I mentally plan what I will say when I arrive to explain clearly and professionally.",
    },
  },
  {
    id: 4,
    section: 1,
    tag: "MONEY & RISK · A NEW OPPORTUNITY",
    text: "Someone offers you a business deal — good potential but some risk. You have not thought about it before. What happens inside you?",
    instruction: "Notice your inner reaction, not what you think you should feel.",
    options: {
      A: "Immediate excitement — I am already thinking about how to make it work.",
      B: "Curiosity and buzz — I want to tell someone about it and talk it through.",
      C: "Caution — I want to think about how it affects my current stability first.",
      D: "Scepticism — I want to see the numbers, the plan, and the downside risk.",
    },
  },
  {
    id: 5,
    section: 1,
    tag: "SELF-IMAGE · HOW OTHERS SEE YOU",
    text: "If your closest friends described you in one word, which of these is most likely?",
    instruction: "Ask yourself honestly — not who you want to be, but who you actually are right now.",
    options: {
      A: "Driven — they know I always find a way to get what I want.",
      B: "Fun — I am the one who brings energy and makes things interesting.",
      C: "Reliable — they know I will always be there when it matters.",
      D: "Thorough — I never miss a detail and I think before I speak.",
    },
  },
  {
    id: 6,
    section: 2,
    tag: "LEARNING & GROWTH · WATCHING SOMEONE FAIL",
    text: "You watch a fellow entrepreneur make a mistake you can clearly see. What do you do?",
    instruction: "Go with what you would naturally do, not what is polite.",
    options: {
      A: "I tell them directly — wasting time on a wrong path is worse than a hard truth.",
      B: "I share my experience enthusiastically and try to uplift them.",
      C: "I wait until they are ready to hear it — I do not want to discourage them.",
      D: "I share a structured observation only if they ask — I do not want to overstep.",
    },
  },
  {
    id: 7,
    section: 2,
    tag: "CONFLICT · AN ARGUMENT",
    text: "You disagree with someone during a group discussion. The tension is visible. What do you do?",
    instruction: "This reveals a lot — be honest with yourself.",
    options: {
      A: "I hold my ground. I do not back down unless I see clear proof I am wrong.",
      B: "I try to defuse it with humour or energy — I hate heavy tension.",
      C: "I soften my position to keep the peace, even if I still partly disagree.",
      D: "I ask everyone to pause and look at the facts objectively before continuing.",
    },
  },
  {
    id: 8,
    section: 2,
    tag: "DAILY LIFE · UNEXPECTED FREE TIME",
    text: "You suddenly have an unexpected free afternoon with nothing planned. What do you do?",
    instruction: "Your unplanned moments reveal your true nature.",
    options: {
      A: "I fill it immediately — there is always something productive I can do.",
      B: "I call someone or head somewhere social — I do not enjoy being alone for long.",
      C: "I rest, watch something I enjoy, or spend quiet time with family.",
      D: "I organise something I have been putting off — my files, plans, or notes.",
    },
  },
  {
    id: 9,
    section: 2,
    tag: "MONEY & RISK · SPENDING ON YOURSELF",
    text: "You have just had a good month financially. How do you treat yourself?",
    instruction: "Your relationship with money tells a lot about your mindset.",
    options: {
      A: "I reinvest it straight away — more growth, more resources, more momentum.",
      B: "I celebrate with people I love — a dinner, a trip, something memorable.",
      C: "I save most of it — security first, comfort later.",
      D: "I allocate it carefully — some saved, some invested, expenses tracked.",
    },
  },
  {
    id: 10,
    section: 2,
    tag: "SELF-IMAGE · YOUR DEEPEST FEAR",
    text: "Deep down, what scares you the most in life?",
    instruction: "The most honest question in this assessment. Go with your gut — do not filter.",
    options: {
      A: "Being ordinary. Leaving no mark. Having lived without real impact.",
      B: "Being forgotten. Losing the people and connections that make life meaningful.",
      C: "Losing stability. Not being able to provide safety for my family.",
      D: "Making a serious mistake I could have prevented if I had been more careful.",
    },
  },
  {
    id: 11,
    section: 3,
    tag: "BUSINESS INSTINCT · A SLOW MONTH",
    text: "Your business has a slow month — fewer enquiries, less revenue. What goes through your mind first?",
    instruction: "Your first reaction — not your plan — is what we are looking at.",
    options: {
      A: "Anger at myself — then immediate action. I will not wait for things to improve.",
      B: "Worry — then I reach out to people in my network to find what I am missing.",
      C: "Anxiety — but I hold steady and trust that things will stabilise.",
      D: "I go through my data to figure out exactly where the drop came from.",
    },
  },
  {
    id: 12,
    section: 3,
    tag: "PEOPLE & RELATIONSHIPS · MEETING SOMEONE IMPRESSIVE",
    text: "You meet someone impressive at a business event — smarter and more successful than you. What do you feel?",
    instruction: "Your emotional reaction reveals your inner world.",
    options: {
      A: "Competitive energy — I want to reach their level or surpass them.",
      B: "Genuine excitement — I want to connect with them and learn their story.",
      C: "Warmth and respect — I admire them without feeling threatened.",
      D: "Curiosity — I want to understand exactly how they built what they built.",
    },
  },
  {
    id: 13,
    section: 3,
    tag: "LEARNING & GROWTH · MAKING A MISTAKE",
    text: "You make a significant mistake in your business — a bad decision that costs you money or a client. How do you process it?",
    instruction: "This is about emotional recovery, not strategy.",
    options: {
      A: "I move on fast — I feel it briefly, then I am already on the next move.",
      B: "I talk about it with someone I trust — getting it out helps me heal.",
      C: "I carry it quietly for a while — it takes time for me to let things go.",
      D: "I analyse it thoroughly — I need to understand every factor before I can move on.",
    },
  },
  {
    id: 14,
    section: 3,
    tag: "DAILY LIFE · LEARNING STYLE",
    text: "You want to learn something new for your business. What feels most natural?",
    instruction: "How you learn reflects how you think.",
    options: {
      A: "Watch a short video, pick the key insight, and try it immediately.",
      B: "Join a live session or community — learning is better with others.",
      C: "Go through a full course at my own pace, no rush.",
      D: "Read articles, take notes, cross-reference — I want depth, not just surface.",
    },
  },
  {
    id: 15,
    section: 3,
    tag: "CONFLICT · SAYING NO",
    text: "A client asks for something outside your scope — extra work, no extra pay. What do you do?",
    instruction: "This reveals how you protect your boundaries.",
    options: {
      A: "I say no clearly and immediately — my time and energy are non-negotiable.",
      B: "I try to redirect warmly — I want them happy but I also want to keep the relationship.",
      C: "I likely do it this time — I hate disappointing someone I care about.",
      D: "I check my agreement and communicate my policy clearly and professionally.",
    },
  },
  {
    id: 16,
    section: 4,
    tag: "BUSINESS INSTINCT · SPOTTING A GAP",
    text: "You notice a gap in the market — something nobody in your area is doing well. What happens next?",
    instruction: "Do you act, talk, wait, or plan?",
    options: {
      A: "I am already mentally calculating how to enter that market as fast as possible.",
      B: "I get excited and start telling people — testing the idea out loud.",
      C: "I observe it carefully for a while before deciding to do anything.",
      D: "I research it systematically — competition, margins, demand — before I commit.",
    },
  },
  {
    id: 17,
    section: 4,
    tag: "SELF-IMAGE · BEING PRAISED",
    text: "Someone publicly praises your work in a group setting. How do you feel inside?",
    instruction: "Your relationship with recognition is deeply personal.",
    options: {
      A: "Good — but only if the results actually earned it. Empty praise means nothing.",
      B: "Genuinely happy — I love being acknowledged and I will return the energy.",
      C: "Grateful but a little uncomfortable — I prefer private appreciation.",
      D: "Pleased, but I immediately wonder if it is accurate and well-founded.",
    },
  },
  {
    id: 18,
    section: 4,
    tag: "MONEY & RISK · A BIG INVESTMENT",
    text: "You are considering spending Rs. 50,000 on a business tool or course. You are not 100% sure it will work. What do you do?",
    instruction: "Notice what you feel, not just what you calculate.",
    options: {
      A: "If it could accelerate results, I pay and move — hesitation is the real cost.",
      B: "I ask people who have tried it, get their vibe, then decide based on trust.",
      C: "I wait until I feel more certain — I do not like financial uncertainty.",
      D: "I research reviews, ROI data, and alternatives before committing.",
    },
  },
  {
    id: 19,
    section: 4,
    tag: "PEOPLE & RELATIONSHIPS · LEADING A GROUP",
    text: "You are part of a group project and nobody is stepping up to lead. What do you do?",
    instruction: "Leadership instinct shows up without thinking.",
    options: {
      A: "I naturally step in and start directing — someone has to do it.",
      B: "I start energising the group, get everyone talking and motivated.",
      C: "I support whoever is willing to lead — I work well in the background.",
      D: "I suggest a clear process and structure before anyone moves.",
    },
  },
  {
    id: 20,
    section: 4,
    tag: "BUSINESS INSTINCT · YOUR ENDGAME",
    text: "Five years from now — your business is going well. Close your eyes. What does that picture actually look like?",
    instruction: "This is about your heart, not your strategy. What truly matters to you?",
    options: {
      A: "I am the dominant player in my space. People know my name and respect what I built.",
      B: "I have a community of people whose lives I have genuinely changed. They love what I do.",
      C: "My family is secure, my business is stable, and I sleep well at night.",
      D: "Everything runs like clockwork — my systems are so good the business almost runs itself.",
    },
  },
];

export const DISC_PROFILES: Record<string, DiscProfile> = {
  D: {
    letter: "D",
    name: "Dominant",
    nickname: "The Fire Starter",
    color: "#c94c4c",
    dimColor: "rgba(201,76,76,0.12)",
    edge: "You take action when others are still thinking. That gap between decision and execution is your advantage over 90% of entrepreneurs.",
    pattern: "You carry urgency like oxygen. Slowing down feels like dying. You process pain quickly and move on — sometimes too quickly to learn from it.",
    watch: "You move so fast that you sometimes break trust — with your team, your clients, and yourself. Your biggest enemy is not the market. It is the version of you that burns bridges while building empires.",
    prescription: "Your weapon is boldness — but boldness without consistency is just noise. Pick one offer, one audience, one message. Do it every single day for 90 days. Tamil Business Tribe will help you build the system that matches your speed without losing your people.",
    traits: {
      summary: "High initiative, result-oriented, and naturally takes control of situations.",
      communication: "Direct, brief, and focuses on 'what' rather than 'how'.",
      decisionMaking: "Fast and decisive, often prioritizing speed over consensus.",
      stressResponse: "Becomes demanding or blunt under pressure.",
      leadership: "Commanding and goal-driven, expects results quickly.",
      growth: "Learning to listen more and valuing the process as much as the outcome.",
    },
  },
  I: {
    letter: "I",
    name: "Influential",
    nickname: "The Heartbeat",
    color: "#c9a84c",
    dimColor: "rgba(201,168,76,0.12)",
    edge: "You can build audiences that competitors cannot buy with money. Loyalty follows your energy, your warmth, and your story.",
    pattern: "You think out loud. Connection charges you completely. Loneliness drains you faster than anything else. You feel everything — highs and lows — more intensely than most.",
    watch: "You start ten things and finish three. Your emotional highs and lows affect your business consistency in ways you may not realise. The clients who love you most are often waiting on follow-ups you forgot about.",
    prescription: "Your weapon is storytelling — but stories need a system behind them. Build one content schedule, one WhatsApp follow-up sequence, and one referral ask you give every happy client. Tamil Business Tribe will help you systematise what you already do naturally.",
    traits: {
      summary: "Enthusiastic, optimistic, and highly skilled at building relationships.",
      communication: "Expressive, persuasive, and focuses on people and emotions.",
      decisionMaking: "Influenced by gut feeling and the impact on people.",
      stressResponse: "May become overly emotional or disorganized under pressure.",
      leadership: "Inspiring and democratic, leads through motivation.",
      growth: "Focusing on follow-through and organizational consistency.",
    },
  },
  S: {
    letter: "S",
    name: "Steady",
    nickname: "The Quiet Root",
    color: "#4cad7a",
    dimColor: "rgba(76,173,122,0.12)",
    edge: "Client retention is your superpower. People stay with you for years because they trust you at a level that goes beyond the product or service.",
    pattern: "You carry other people's weight quietly and without complaint. Peace matters to you more than most people around you realise. You recover slowly from disappointment.",
    watch: "You are likely underpricing yourself and over-delivering without being asked. You say yes when you mean no. You wait to be invited when you should be leading.",
    prescription: "Your weapon is referrals — but you need to ask for them out loud. Set a rule: after every positive client interaction, ask for one referral. Just one. Tamil Business Tribe will help you build the confidence and the script to ask without feeling like you are imposing.",
    traits: {
      summary: "Patient, reliable, and deeply committed to group harmony.",
      communication: "Gentle, listening-oriented, and prefers calm environments.",
      decisionMaking: "Methodical and slow, seeks security and consensus.",
      stressResponse: "May become passive or resistant to change when stressed.",
      leadership: "Supportive and collaborative, a true servant leader.",
      growth: "Learning to set boundaries and take decisive risks.",
    },
  },
  C: {
    letter: "C",
    name: "Conscientious",
    nickname: "The Architect",
    color: "#4c82c9",
    dimColor: "rgba(76,130,201,0.12)",
    edge: "You build things that actually work. No corners cut, no promises broken, no shortcuts that come back to hurt you later.",
    pattern: "You need to understand things fully before you can trust them. That depth is both your greatest gift and your most persistent barrier. You are harder on yourself than anyone else ever is.",
    watch: "You are probably sitting on ideas, products, or offers that are 80% ready but have not launched because they are not 100% perfect yet. Perfection is procrastination wearing a professional mask.",
    prescription: "Your weapon is authority content — detailed, accurate, educational posts that make people trust you before they ever meet you. But set one rule: if something is 70% ready, it launches. Tamil Business Tribe will push you to execute, not just plan.",
    traits: {
      summary: "Analytical, precise, and high standard for quality and accuracy.",
      communication: "Fact-based, detailed, and prefers written clarity.",
      decisionMaking: "Evidence-driven, needs all data before committing.",
      stressResponse: "Becomes overly critical or withdrawn under pressure.",
      leadership: "Quality-focused and structured, leads through expertise.",
      growth: "Learning that 'done is better than perfect' and trusting intuition.",
    },
  },
};

export const BLEND_TITLES: Record<string, string> = {
  "DI": "The Dynamic Achiever",
  "ID": "The Charismatic Leader",
  "DS": "The Practical Driving Force",
  "SD": "The Reliable Strategist",
  "DC": "The Strategic Executor",
  "CD": "The Precise Architect",
  "IS": "The Compassionate Connector",
  "SI": "The Supportive Energizer",
  "IC": "The Persuasive Analyst",
  "CI": "The Systematic Communicator",
  "SC": "The Quality-Focused Partner",
  "CS": "The Detail-Oriented Anchor",
  "Balanced": "The Adaptive All-Rounder"
};
